### ISSUE TITLE
Content encoding support for Requests

### ISSUE THREAD

**Issue by RishiRamraj** [Pylons/webob#102]
While I see support for content encodings in the response, I do not see any for request objects. However, gzipping large requests should be possible, as per the HTTP/1.1 spec (assuming I'm reading it correctly):

"If the content-coding of an entity in a request message is not acceptable to the origin server, the server SHOULD respond with a status code of 415 (Unsupported Media Type)."

I'm not sure if modern browsers support these sorts of requests. Should this feature be implemented?

**Comment by bertjwregeer** [comment]
Unfortunately due to limitations in the WSGI spec, this is not supported by WSGI itself.

**Comment by piotr-dobrogost** [comment]
> Unfortunately due to limitations in the WSGI spec, this is not supported by WSGI itself.

Some relevant links with more information on the subject:

[Details on WSGI 1.0 amendments/clarifications.](http://blog.dscpl.com.au/2009/10/details-on-wsgi-10-amendmentsclarificat.html) – Graham Dupleton's blog post where he talks about input filters.

[Apache lags when responding to gzipped requests](http://stackoverflow.com/q/1559416/95735)  – answer by Graham Dupleton on Stackoverflow.

**Comment by RishiRamraj** [comment]
Awesome, thanks for the info!
