### ISSUE TITLE
webob.Request escapes safe characters in PATH_INFO, changing its semantics

### ISSUE THREAD

**Issue by rbu** [Pylons/webob#111]
According to RFC 3986, https://tools.ietf.org/html/rfc3986#section-3.3:

> ```
>   sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
>              / "*" / "+" / "," / ";" / "="
>    ...
>   pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
> ```
> 
>    Aside from dot-segments in hierarchical paths, a path segment is
>    considered opaque by the generic syntax.  URI producing applications
>    often use the reserved characters allowed in a segment to delimit
>    scheme-specific or dereference-handler-specific subcomponents.  For
>    example, the semicolon (";") and equals ("=") reserved characters are
>    often used to delimit parameters and parameter values applicable to
>    that segment.  The comma (",") reserved character is often used for
>    similar purposes.  For example, one URI producer might use a segment
>    such as "name;v=1.1" to indicate a reference to version 1.1 of
>    "name", whereas another might use a segment such as "name,1.1" to
>    indicate the same.  Parameter types may be defined by scheme-specific
>    semantics, but in most cases the syntax of a parameter is specific to
>    the implementation of the URI's dereferencing algorithm.

Unfortunately, WebOb.Request escapes some of the characters in the 'sub-delims' set, such as ";" and "="

> print webob.Request.blank("http://example.com/path/segment;v=1.1/other,1.1/fnord?fnord=23")
> GET /path/segment%3Bv%3D1.1/other,1.1/fnord?fnord=23 HTTP/1.0
> Host: example.com:80

In older versions of this RFC (1808, 2396), this has been specified as "Object parameters", see https://tools.ietf.org/html/rfc1808#section-2.1 

We noticed this issue when sending requests to Tomcat who uses the semicolon parameters to add a "jsessionid" to the URL when cookies cannot be used. In this setting, "GET /fnord;jsessionid=1234?id=23" is not the same as "GET /fnord%3Bjsessionid%3D1234?id=23", as URL decoding of the path info on the server (correctly) happens after the reserved characters have been interpreted.

Besides the semicolon and equal sign which are important in our case, some more characters should not be automatically escaped (according to the RFC):

> print webob.Request.blank("http://example.com/AZaz09-._~!$&'()*+,;=:@%23?fnord=23")
> GET /AZaz09-._%7E%21$&%27%28%29%2A+,%3B%3D:@%23?fnord=23 HTTP/1.0
> Host: example.com:80

Note: This issue has been partially solved in aaa0348f09774b8a521704d872af953fa6017899 / https://bitbucket.org/ianb/webob/issue/5

**Comment by bertjwregeer** [comment]
This was fixed in https://github.com/Pylons/webob/pull/291

**Comment by rbu** [comment]
Thanks for finally resolving this! :+1:
