### ISSUE TITLE
304 response should return no content-type header by default

### ISSUE THREAD

**Issue by rapto** [Pylons/webob#112]
In our application, some ajax calls return xml. The second time the same request is issued, we detect the etag is the same, so we return HTTPNotModified().

The problem is that a 'content-type: text/html' is added, making the response unusable as XML (at least in Chrome, which leaves responseXML empty for a non text/xml response). This happens even if a content_type is added in the constructor: HTTPNotModified(content_type='text/xml').

I have not studied the corner cases in the standard, but I feel that HTTPNotModified should return no content-type or the one explicitly provided, at least.

I'll try to submit a patch as soon as I can.

**Comment by bertjwregeer** [comment]
Do you have an example minimal test case that showcases the issue? I am trying to reproduce this, but by default `HTTPNotModified()` does not set any `content_type`, nor any headers for that matter other than the 304 status code.

If this is no longer an issue please close this bug report.

**Comment by bertjwregeer** [comment]
Test code used:

    def test_HTTPNotModified_headers():
        _status = None
        _headers = None
    
        def start_response(status, headers, exc_info=None):
            print(status)
            print(headers)
    
        environ = {
           'wsgi.url_scheme': 'HTTP',
           'SERVER_NAME': 'localhost',
           'SERVER_PORT': '80',
           'REQUEST_METHOD': 'GET',
           'HTTP_ACCEPT': 'text/html'
        }
        
        excep = HTTPNotModified()
        resp = excep(environ, start_response)
        print(resp)

**Comment by bertjwregeer** [comment]
Closing issue due to no followup. If this is still an issue please re-open.
