### ISSUE TITLE
webob chokes on %c5 in url when url_encoding is the default UTF-8

### ISSUE THREAD

**Issue by tisdall** [Pylons/webob#114]
```
  File "/sites/env/lib/python3.3/site-packages/WebOb-1.2.3-py3.3.egg/webob/request.py", line 167, in encget
    return bytes_(val, 'latin-1').decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 18: invalid continuation byte
```

I was trying to pass short binary data via URL encoding and got this error.  

So, I can do fun things like this:  http://www.pylonsproject.org/abou%c5t/pylons

```
Server Error

An error occurred. See the error logs for more information. (Turn debug on to display exception reports here)
```

Essentially throw a server error on sites running Pyramid.

**Comment by mcdonc** [comment]
See https://github.com/pypa/warehouse/blob/master/warehouse/config.py#L65-L87 (junk_encoding_tween_factory) for the current state of where webob might raise a UnicodeDecodeError as mentioned in https://github.com/Pylons/webob/issues/114#issuecomment-22433881
