### ISSUE TITLE
Incorrect detection of status_code in Request

### ISSUE THREAD

**Issue by igrishaev** [Pylons/webob#121]
When the Response was created from stream, the _status_code__get() method cannot detect status code properly, becourse it tries to sptlit start line and convert first element  to int (HTTP/1.1 in my case).

```
resp = """HTTP/1.1 200 OK
Cache-Control: private, no-store,No-Store
Content-Length: 1024
Content-Type: application/octet-stream
ETag: ""
Server: Microsoft-IIS/7.5
content-disposition: attachment; filename=1kb.txt
X-AspNet-Version: 2.0.50727
X-Powered-By: ASP.NET
Date: Thu, 19 Sep 2013 13:57:07 GMT

Some data...
"""

s = StringIO()
s.write(resp)
s.seek(0)

r = Response.from_file(s)
print r.status_code

Traceback (most recent call last):
  File "<string>", line 254, in run_nodebug
  File "...", line 45, in <module>
    print r.status_code
  File "C:\Python27\lib\site-packages\webob\response.py", line 272, in _status_code__get
    return int(self._status.split()[0])
ValueError: invalid literal for int() with base 10: 'HTTP/1.1'
```

**Comment by ei-grad** [comment]
Webob they said. HTTP Request/Response classes they said. But they just invented their own HTTP Response format without HTTP-Version field... ![facepalm](http://i.imgur.com/iWKad22.jpg)

**Comment by bertjwregeer** [comment]
@igrishaev Thanks for the report, will take a look at it.

@ei-grad That isn't helpful at all.

**Comment by ei-grad** [comment]
1. "20 Sep 2013"
2. I just saw a new protocol instead of HTTP in tests, and understood that I can't help there. :-(

**Comment by igrishaev** [comment]
Bert, thanks a lot!

**Comment by bertjwregeer** [comment]
@ei-grad I took over as maintainer pretty recently. A simple bump would have been enough for me to take look at it.

**Comment by bertjwregeer** [comment]
======================================================================
    ERROR: tests.test_response.test_file_with_http_version
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/xistence/Projects/webob/.tox/py33/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/Users/xistence/Projects/webob/tests/test_response.py", line 422, in test_file_with_http_version
        eq_(res.status_code, 200)
      File "/Users/xistence/Projects/webob/webob/response.py", line 272, in _status_code__get
        return int(self._status.split()[0])
    ValueError: invalid literal for int() with base 10: 'HTTP/1.1'

Using this test:

    def test_file_with_http_version():
        inp = io.BytesIO(b'HTTP/1.1 200 OK\r\n\r\nSome data...')

        res = Response.from_file(inp)
        eq_(res.status_code, 200)
        eq_(res.status, '200 OK')

Fix is incoming.

**Comment by bertjwregeer** [comment]
@igrishaev If you could test master, I would appreciate it. I'll back port it to 1.5 tonight. Sorry you had to wait so long for a fix.

**Comment by igrishaev** [comment]
@bertjwregeer I can't test the code the moment, sorry. I've done with the project already =) But the diff looks fine and the tests are well. It seems you can close the issue. Thanks.
