### ISSUE TITLE
Accept.best_match doesn't recognize wildcards

### ISSUE THREAD

**Issue by rhymeswithcycle** [Pylons/webob#122]
I would expect that all of the following Accept headers would match a `text/html` content type: `text/html`, `text/*`, `*/*`

However, the latter two don't:

```
In [6]: print Accept('text/html').best_match(['text/html'])
text/html

In [7]: print Accept('*').best_match(['text/html'])
text/html

In [8]: print Accept('*/*').best_match(['text/html'])
None

In [9]: print Accept('text/*').best_match(['text/html'])
None
```

Is this intentional behaviour for some reason? If not, I'm happy to write tests and see if I can make a patch too.

**Comment by bertjwregeer** [comment]
@dobesv is correct, you want `MIMEAccept`. `Accept` is the base class.
