### ISSUE TITLE
Response wrongly keeps charset in Content-Type header

### ISSUE THREAD

**Issue by wosc** [Pylons/webob#130]
```
>>> response = webob.Response()
>>> response.content_type = 'image/jpeg'
>>> response.headers['Content-Type']
'image/jpeg; charset=UTF-8'
```

I guess the reason is that the `content_type` property preserves parameters if the new value does not contain any, so the charset is not removed from the header when setting a content type without parameters later on.

**Comment by bertjwregeer** [comment]
This was fixed in #261. Keeping any Content-Type parameters will be removed in WebOb 1.9.
