### ISSUE TITLE
Accept matching against wildcard offers is not allowed

### ISSUE THREAD

**Issue by ltvolks** [Pylons/webob#155]
Wildcards cannot be used in 'offered' content types to search for a match:

```python
>>> from webob.acceptparse import MIMEAccept
>>> accept = MIMEAccept('text/*')

>>> 'text/plain' in accept
True

# Expect this to be True
>>> 'text/*' in accept
ValueError: The application should offer specific types, got 'text/*'

>>> accept.best_match(['text/html', 'text/plain', 'text/json'])
'text/html'

# Expect 'text/html' or 'text/plain' in the absence of quality parameter
>>> accept.best_match(['text/*', 'text/html', 'text/plain'])
ValueError: The application should offer specific types, got 'text/*'

# Expect 'text/*' as the best match
>>> accept.best_match(['text/*', 'foo/bar'])
ValueError: The application should offer specific types, got 'text/*'
```

The behavior and error WebOb provides is explicit and it uses the same [check](https://github.com/Pylons/webob/blob/1.4/webob/acceptparse.py#L320) anywhere it is performing a match:

```python
def _check_offer(offer):
    if '*' in offer:
        raise ValueError("The application should offer specific types, got %r" % offer)
```

This is not insensible, but it does cause an issue with Pyramid's [documented](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html) accept predicate handling: https://github.com/Pylons/pyramid/issues/1407

If you want to define a 'permissive' accept predicate like `text/*`, the Pyramid `AcceptPredicate` essentially boils down to:

```python
return 'text/*' in request.accept
```

`request.accept` is a WebOb `MIMEAccept` instance, so this check will always fail.

**Comment by diefans** [comment]
any chance the fix gets merged?

**Comment by ltvolks** [comment]
@diefans - I never actually submitted a pull request for this (https://github.com/ltvolks/webob/commit/8f49817f64833fc9171e506ad648314dc7d9a246), but will do so.

It does fix https://github.com/Pylons/pyramid/issues/1407, and addresses the basic matching issue here.
