### ISSUE TITLE
concept of tweens

### ISSUE THREAD

**Issue by faassen** [Pylons/webob#176]
I'd like us to introduce the concept of a "tween" to WebOb (as implemented by Pyramid; I also took that idea for Morepath). This because there are several useful tweens that WebOb could potentially include. The Forwarded tween implemented in pull request #175 is an example. 

A tween is a way to do middleware at the WebOb level. A tween is a function (or callable instance) that can wrap a function ``handle(request) -> response``, thereby affecting the request and the response.

If we introduce this concept, we need general documentation that describes the concept. (I volunteer to write it).

We also need some guidelines. If we include a tween in WebOb, should we also include a WSGI middleware based on this tween, or is just the tween enough?

**Comment by bertjwregeer** [comment]
I have no interest in supporting something similar to tweens within WebOb. WSGI middleware maybe.
