### ISSUE TITLE
How do I know what version of webob I have installed?

### ISSUE THREAD

**Issue by Steven121** [Pylons/webob#198]
This command shows it is installed:
$ whatis webob              

How do I find out what version of webob I have installed?

**Comment by bertjwregeer** [comment]
I have no idea what the `whatis` command does.

From within python:

    Python 3.4.3 (default, Apr 13 2015, 18:20:12) 
    [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pkg_resources
    >>> pkg_resources.get_distribution('webob').version
    '1.5.0.dev0'
