### ISSUE TITLE
Read the docs news page is missing 1.4.1 release notes

### ISSUE THREAD

**Issue by edmorley** [Pylons/webob#199]
The v1.4.1 section is missing from http://docs.webob.org/en/latest/news.html

Looks like it only landed on the 1.4 branch:
https://github.com/Pylons/webob/commit/df93e867683a8e652f2e3e3659e1dfab1e35ff21

And not on master:
https://github.com/Pylons/webob/blob/master/docs/news.txt#L82

**Comment by mcdonc** [comment]
Thank you!  That's an articfact of how we do releases.  Older release change logs do not receive updates for minor releases of the branch that represents the major release (e.g. only the changelog for the 1.4 branch sees 1.4.1 change notes, only the changelog for the 1.5 branch sees 1.5.1 change notes, etc).  Apologies, but I don't see this changing.

**Comment by edmorley** [comment]
Thank you for explaining. This is really counter-intuitive though - particularly since in the sidebar on http://docs.webob.org/en/latest/news.html I can see point releases for previous releases (presumably since they hadn't branched yet) & there is no mention of this in the docs or on the homepage, from which the docs are linked.

ie:
1) Go to http://webob.org/
2) On the sidebar where it says "Newest release: 1.4.1", click "What's new"
3) Try to find details of the release mentioned in step 2.
-> Not possible.

Perhaps webob.org needs to be changed instead to link to both the master and branch news pages?

**Comment by mcdonc** [comment]
Oh geez, I'm sorry, I misread the issue.  I thought this was for Pyramid (where 1.4.1 is a very old release).  I'm reopening.

**Comment by bertjwregeer** [comment]
I really wish the "latest" docs actually pointed to a branch instead, rather than to master.

The artifact of how Pyramid does releases has unfortunately also been brought over to WebOb since master has diverged from 1.4-branch significantly.

**Comment by mmerickel** [comment]
That's not true. Pyramid points `/latest` at the latest stable release and has a separate target for `/master`.

@bertjwregeer you should get access to RTD for webob so you can update latest and add new version builds when you do releases.

Our other projects are less-strict on that policy and many have `/latest` pointing to master because we can't be bothered to edit rtd after every release (mostly because those projects don't really have major releases, only minor ones).

**Comment by bertjwregeer** [comment]
Well, if this can be fixed that would be fantastic.

**Comment by stevepiercy** [comment]
@bertjwregeer now that I have RTD access for webob, I poked my head into the Advanced Settings, and see this:

> Default branch:
[1.5-branch]
What branch "latest" points to. Leave empty to use the default value for your VCS (eg. trunk or master).
Default version:
[latest]
The version of your project that / redirects to

If 1.5 is the latest/stable release of webob, then this issue may be closed.

**Comment by bertjwregeer** [comment]
Yeah, I fixed this when I got access to RTD. Didn't close this ticket. Thanks for the update :-)
