### ISSUE TITLE
Parameters included in a DELETE body request are not included in the parameters dictionary

### ISSUE THREAD

**Issue by Hunsu** [Pylons/webob#200]
Fix this issue: https://github.com/Pylons/pyramid/issues/1685

**Comment by bertjwregeer** [comment]
This is according to spec. According to the HTTP RFC's the DELETE request while it allows an entity body it should be ignored because it has no semantic meaning.

Various reverse proxies and proxies will strip the body from an DELETE request.

**Comment by Hunsu** [comment]
Can you give a link to the spec that says that the body should be ignored?

**Comment by bertjwregeer** [comment]
RFC2616, section 4.3:

> "A server SHOULD read and forward a message-body on any request; if the request method does not include defined semantics for an entity-body, then the message-body SHOULD be ignored when handling the request."

Followed by RFC 7231 section 4.3.5:

> "A payload within a DELETE request message has no defined semantics; sending a payload body on a DELETE request might cause some existing implementations to reject the request."
