### ISSUE TITLE
The 1.4.1 release on pypi is 655kb

### ISSUE THREAD

**Issue by jamielennox** [Pylons/webob#201]
For what is supposed to be a small library the pypi release is huge. https://pypi.python.org/pypi/WebOb/1.4.1

The source of this appears to be that a pyc file for py2x, py32, py33, py34 and pypy for each test file is packaged into the pypi download. 

For future releases can we please strip out all the build artifacts.

**Comment by bertjwregeer** [comment]
:-(. Sorry, that's my bad.

**Comment by bertjwregeer** [comment]
Next release of 1.4 will be small again.

**Comment by jamielennox** [comment]
Thank you!
