### ISSUE TITLE
Docs still mention obsolete str_* properties

### ISSUE THREAD

**Issue by dairiki** [Pylons/webob#202]
The [unicode](https://github.com/Pylons/webob/blob/master/docs/index.txt#L175) section of the docs still mention the `str_`* properties.  These are obsolete and raise exceptions if an attempt is made to access them.

Actually, I have a suspicion that the whole *Unicode* section is out of date.  From what I can tell, currently, most methods that return text strings mostly assume *utf8* encoding (regardless of any encoding specified in `environ[CONTENT_TYPE]` (or `request.charset`).  (See also `request.decode()` and `request._check_charset()` and the [News for release 1.2a2](https://github.com/Pylons/webob/blob/9b79f5f913fb1f07c68102a2279ed757a2a9abf6/docs/news.txt#L372).

**Comment by bertjwregeer** [comment]
The docs need a lot of work. I haven't had the time to go over them yet. I will happily accept pull requests :-)

**Comment by dairiki** [comment]
I'd be happy to produce a trivial PR which just removes the references to the `str_*` properties, if that would be useful.

I don’t  currently feel qualified to update the rest of the docs w.r.t. character encoding/unicode, since I’m not totally sure what the intended behavior/recommended usage is.

**Comment by bertjwregeer** [comment]
I have removed the references for now. More docs work will have to be done in the future.
