### ISSUE TITLE
WebOb >=1.5 'Set-Cookie' strings are not backwards compatible to 1.4

### ISSUE THREAD

**Issue by dakra** [Pylons/webob#212]
I use WebOb in a pyramid app that sets an auth_tkt cookie.
Pre 1.5 it returns
`Set-Cookie: auth_tkt="auth_token_here...!userid_type:int"`
but in 1.5+ the quotes are gone:
`Set-Cookie: auth_tkt=auth_token_here...!userid_type:int`

Not sure if that's an bug or not but should at least be documented.

**Comment by bertjwregeer** [comment]
Quotes are not required in cookie strings, and never have.

    Set-cookie: "somecookie"

is the exact same, and dealt with the exact same way as:

    Set-cookie: somecookie

**Comment by bertjwregeer** [comment]
Do note: WebOb will fall back to quoting the cookie if and only if it happens to contain spaces in the cookie value, which is contra-spec and will raise a warning. In the future WebOb will no longer allow anyone to set cookie values that are not valid according to the specifications.

**Comment by bertjwregeer** [comment]
Just as a follow-up on the title, they are backwards compatible. WebOb 1.4 will handle the newly generated cookies without issues, and vice-versa.

**Comment by dakra** [comment]
Maybe 'backwards incompatible' was a the wrong phrase to use.
I didn't meant that the new cookies are not working with the old version of WebOb or vice versa but
just that they are generated now different.
We have some other/external code that parsed the Set-Cookie to extract the auth_tkt and
that broke because 1.5+ doesn't quote the cookie value anymore.
If with or without quotes is ok according to the rfc I just adjust that parsing code to accept both. :)

**Comment by bertjwregeer** [comment]
I've added a note to the change notes, it's currently on the branch docs/cleanup which is a greater work I am working on to clean up all of the documentation within WebOb itself.

So it will be in the change log for when 1.5.0 is finally released.
