### ISSUE TITLE
default_content_type does not match documented value

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/webob#213]
As it currently stands, `default_conten_type` is set to `text/html`, overtime this has become a thorn in the side of WebOb, as can be seen by the following ticket numbers: #205, #204, #130, #112 

There is an escape hatch however, in that the documentation clearly states:

> The status defaults to '200 OK'. The **content_type does not default to anything, though if you subclass Response and set default_content_type you can override this behavior.**

*Emphasis mine*

Now, I have a bad feeling that if I change it back to match the documentation, it is going to break many different projects, however I can't be sure about that until I actually try it and start getting reports of what broke ;-)

Input requested!

/cc: @mcdonc, @tseaver, @mmerickel, @dstufft

**Comment by bertjwregeer** [comment]
Change was made in this commit: https://github.com/Pylons/webob/commit/638faf4fae36a015442fbc0bf48f2415fe3cbb34

No justification was added as to why the change was made.

**Comment by bjmc** [comment]
I was just bitten by this bug now, when my HTTP 204 responses surprisingly turn out to have Content-Type': 'text/html; headers.

:+1: for fixing this to match documentation. If you are worried about breaking users who depend on the bad behavior, then throw a `DeprecationWarning()` for a while and then fix it.

**Comment by tseaver** [comment]
Pyramid already [subclasses `Response`](https://github.com/Pylons/pyramid/blob/be5beb748db85d3861da703daac4461703c5240f/pyramid/response.py#L28-L30), and so could easily set `default_content_type` back if needed.

**Comment by bertjwregeer** [comment]
@tseaver In Pyramid we would actually want to go back to having no `default_content_type` as well, because it is causing issues for templating because we don't know if the user set the `content_type` or if it is the `default_content_type`. There are some longstanding issues open on Pyramid regarding this as well.

Either way I think it needs to be planned, and carefully thought about.

**Comment by bertjwregeer** [comment]
Another reason this should be removed and excised: https://github.com/Pylons/webob/issues/237#issuecomment-200971278

**Comment by bertjwregeer** [comment]
This is not a good route to go. See #238. #261 lays some of the groundwork, and at least includes some fixes for this.
