### ISSUE TITLE
bugs in exc.py

### ISSUE THREAD

**Issue by hzweveryday** [Pylons/webob#221]
in https://github.com/Pylons/webob/blob/master/webob/exc.py

class HTTPNotAcceptable(HTTPClientError) line 719, template=..., should it be body_template_obj=...

class HTTPUnsupportedMediaType(HTTPClientError) line 847, template_obj = ..., should it be body_template_obj=...

besides,
class HTTPNotImplemented(HTTPServerError): line 1029,  template=..., should it be body_template_obj=...

**Comment by bertjwregeer** [comment]
Thanks for the report. Will get a fix out shortly.
