### ISSUE TITLE
Homepage shouldn't say 0 issues exist

### ISSUE THREAD

**Issue by ismail-s** [Pylons/webob#224]
On the [project homepage](http://webob.org/), it says:

```
Zero known issues (reported bugs are always fixed ASAP).
```

Clearly this is no longer true and should be changed (or at least somehow linked to github).

**Comment by bertjwregeer** [comment]
That entire website needs an overhaul, unfortunately I haven't had the time to do so.

**Comment by bertjwregeer** [comment]
Also, do you have any particular issues you have in mind that you'd want to see fixed? Maybe I can prioritise it.

**Comment by ismail-s** [comment]
No, I was just navigating to the webob docs and noticed this issue in the process. Thought I'd just let you know.

**Comment by stevepiercy** [comment]
This has been fixed.

Also I now have admin access to webob.org, and there is a new repo for webob.org marketing website issues:
https://github.com/Pylons/webob.org
