### ISSUE TITLE
Response header "Location" should use urlencode

### ISSUE THREAD

**Issue by wosc** [Pylons/webob#248]
When you assign a unicode value to any response header, webob tries to encode it with latin-1 (https://github.com/Pylons/webob/blob/master/webob/descriptors.py#L145). But URLs often are utf-8 or worse, so that breaks when they are used in redirects in the `Location` header. If I'm reading the RFCs right (see e.g. https://stackoverflow.com/a/7654605), the `Location` header should use urlencode instead of latin-1.

I'm willing to come up with a PR for this, but I'd like someone more knowledgeable to confirm that's the way to go first. :)

**Comment by bertjwregeer** [comment]
Unicode is not allowed in headers, only latin-1, so even URL's have to be latin-1. Using urlencode would probably be a good idea. I'd be open to seeing a PR with the fix, so long as the end result is that the header values are all latin-1.

**Comment by wosc** [comment]
https://github.com/Pylons/webob/pull/249 is a stab at this.

**Comment by wosc** [comment]
The more I think about this, it turns out to be _really hard_ to do in the general case. For example: query parameters that already urlencoded versus those that are not.

**Comment by bertjwregeer** [comment]
Unless there is some interest in this moving forward, and there is a way to do this without causing double percent encoding issues, I am closing this issue.
