### ISSUE TITLE
webob.Request.from_file parsing failure

### ISSUE THREAD

**Issue by rtilder** [Pylons/webob#250]
webob.Request's from_file method seems have to an incorrect call to str.split()

```
    import io, webob
    s = "HTTP/1.0 200 Ok\nConnection: close\n\n"
    webob.Request.from_file(io.BytesIO(s))  # success
    s = "HTTP/1.0 404 Not Found\nConnection: close\n\n"
    webob.Request.from_file(io.BytesIO(s))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/rtilder/sandbox/horked_from_file/lib/python2.7/site-packages/webob/response.py", line 179, in from_file
        (http_ver, status_num, status_text) = status.split()
    ValueError: too many values to unpack
```

Relevant code is [here](https://github.com/Pylons/webob/blame/master/webob/response.py#L179).  The existing code works just fine on a 200 response but not on the faux 404 

`    (http_ver, status_num, status_text) = status.split()`

I suspect that this is inadvertent and that the following was probably intended.

`    (http_ver, status_num, status_text) = status.split(None, 2)`

I was a little surprised I ran into this until I realized that parsing HTTP responses is probably not a terribly common use case.

**Comment by mmerickel** [comment]
You're parsing responses and linked to `webob.response` code but your code example uses `Request.from_file`. Is that actually correct?

**Comment by bertjwregeer** [comment]
`Request.from_file` is doing the right thing: https://github.com/Pylons/webob/blob/master/webob/request.py#L1208

I've fixe this issue in https://github.com/Pylons/webob/commit/17e170d428c6b43a07fbdc36608950cc39cb462e and added a test in https://github.com/Pylons/webob/commit/9aae43c31a4075cf33f11de00b24dceaea66d4d0 so this can't regress.

Thanks for reporting. I'll back port this to 1.6 this weekend.

**Comment by rtilder** [comment]
Sorry about the mispasted code.  webob.Request.from_file parsing correctly, yes.  webob.Response.from_file fails.  Thanks for the quick fix.
