### ISSUE TITLE
Flip if PY3/else (PY2) statements

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/webob#277]
We want to execute the stuff on PY2 when we are running on PY2, otherwise always run the newer code. This way we don't start failing when Python 4 comes around.

**Comment by ztane** [comment]
or rather use `PY3 = sys.version_info[0] > (3,)`, done.

**Comment by bertjwregeer** [comment]
Maybe.

**Comment by ztane** [comment]
The original code is a `six`ism, there is no other reason for it to be like that, and I've complained about the behaviour in `six`s bug tracker; notably `six` also has `PY34` constant that is true for 3.4+, and also Python 4 (where `PY3` would  be again False).

**Comment by mmerickel** [comment]
Pyramid already takes the original approach. Making PY3 match if the version is 4 would be silly and unreadable, despite being the simpler fix.

**Comment by bertjwregeer** [comment]
This has been fixed with: https://github.com/Pylons/webob/pull/319
