### ISSUE TITLE
Default charset does not apply to JSON responses

### ISSUE THREAD

**Issue by href** [Pylons/webob#298]
I've tested WebOb 1.7rc1 with Morepath and I've noticed that the default UTF-8 charset of the response only applies to text responses:

```python
>>> from webob import Response
>>> Response("{}", content_type="text/plain")
<Response at 0x100f188d0 200 OK>
>>> Response("{}", content_type="application/json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/denis/.virtualenvs/morepath/lib/python3.5/site-packages/webob/response.py", line 311, in __init__
    "You cannot set the body to a text value without a "
TypeError: You cannot set the body to a text value without a charset
```

Now I have no problem setting the charset of JSON responses explicitly (and as of today Morepath does), but I was wondering if this might be a bug.

I would have expected that the JSON response also uses the default charset defined on the Response class.

**Comment by ztane** [comment]
#196

**Comment by mmerickel** [comment]
It appears that `default_body_encoding` is not being used in the `__init__`. This is probably a bug. If you were doing `response.text = "{}"` things should work fine.

As far as the charset, you can see the linked issues from @ztane to understand that 1.7 explicitly changes this behavior in webob with regard to `application/json`.

**Comment by bertjwregeer** [comment]
`default_body_encoding` is not used in in `Response()` on purpose. This is not a bug. Passing a body that is "text" is not supported if the Content-Type doesn't have a charset. Pass it as `text` instead

Like so:

```
>>> res = Response(text='{}', content_type='application/json') 
>>> res.body
b'{}'
```

When passing JSON, I would recommend:

```
>>> res = Response(json_body={}, content_type='application/json')
>>> res.body
b'{}'
```

Or

```
>>> res = Response(json_body={})
>>> res.content_type
'application/json'
>>> res.body
b'{}'
```

**Comment by bertjwregeer** [comment]
```
Response("{}", content_type="text/plain")
```

Automatically adds the default charset:

```
>>> res = Response("{}", content_type="text/plain")
>>> res.headers['Content-Type']
'text/plain; charset=UTF-8'
```

Which allows you to set `body` to a "text" object to not break what has been allowed since WebOb 1.1. However I still fully believe that passing a body that is not a bytes object is something that might cause more issues than it is worth.

**Comment by href** [comment]
Ok I understand. Thanks for clearing this up for me - and sorry for missing the existing issues.

**Comment by bertjwregeer** [comment]
I've documented this better in: http://docs.webob.org/en/1.7-branch/whatsnew-1.7.html#backwards-incompatibility as well documenting it in http://docs.webob.org/en/1.7-branch/api/response.html#webob.response.Response

Hopefully this will help other users that may run into the same issue.
