### ISSUE TITLE
pytest.param AttributeError when py.test version < 3.1.0

### ISSUE THREAD

**Issue by whiteroses** [Pylons/webob#322]
With py.test version < 3.1.0, we get this error when we run the tests:

    _____________________ ERROR collecting tests/test_misc.py _____________________
    tests/test_misc.py:42: in <module>
        pytest.param("'", "'", marks=py2only),
    E   AttributeError: 'module' object has no attribute 'param'

`pytest.param` was added to pytest in version 3.1.0. Do you think we should specify `>=3.1.0` for pytest in setup.py?

**Comment by bertjwregeer** [comment]
Sure, feel free to add a pin for it :-)
