### ISSUE TITLE
Change request.accept_encoding accept_property to use an AcceptEncoding class, rather than the generic Accept class

### ISSUE THREAD

**Issue by whiteroses** [Pylons/webob#325]
Currently in request.py, the `Accept*` headers related properties are:

        accept = accept_property('Accept', '14.1', MIMEAccept, MIMENilAccept)
        accept_charset = accept_property('Accept-Charset', '14.2', AcceptCharset)
        accept_encoding = accept_property('Accept-Encoding', '14.3',
                                          NilClass=NoAccept)
        accept_language = accept_property('Accept-Language', '14.4', AcceptLanguage)

The function signature of `accept_property` in acceptparse.py:

    def accept_property(header, rfc_section,
        AcceptClass=Accept, NilClass=NilAccept
    ):

So the only request property of the four that uses the generic `Accept` class for its `AcceptClass` argument is `accept_encoding`:

    >>> Request.blank('/', accept_encoding='compress, gzip').accept_encoding
    <Accept('compress, gzip')>

Having the `Accept` header property identify itself as `MIMEAccept` and the `Accept-Encoding` header property identify itself as `Accept` is confusing in itself, but from what I can see we do need a separate `AcceptEncoding` class, as

1. We'll need to implement `Accept-Encoding`-specific functionality somewhere, e.g. the 'identity' token (https://tools.ietf.org/html/rfc7231#section-5.3.4).

2. As mentioned in https://github.com/Pylons/webob/issues/323, the properties are documented using docstrings and Sphinx autodoc directives, and we can't document things specific to `Accept-Encoding` in the docstrings for the generic `Accept` class.

So for now, I would propose a

    class AcceptEncoding(Accept):
        """[docstring...]"""

and changing the AcceptClass argument for the `accept_encoding` accept_property from `Accept` to `AcceptEncoding`. (We'll add to the `AcceptEncoding` class later.) This would be strictly speaking a breaking change, but it seems unlikely that people would be depending on the class of the `request.accept_encoding` property &mdash; and to keep calling the class for the `Accept-Encoding` header `Accept` (which would involve removing the dependency of all the other classes on the `Accept` class and using it solely for the `Accept-Encoding` header, but keeping the `Accept` name only for backward compatibility) would be very confusing.

Do you think the change would be okay? (If yes, would you like me to add to CHANGES.txt?)

**Comment by bertjwregeer** [comment]
I think this is a change that can be made without any issues. Make a note of it in CHANGES.txt, but I don't think it is backwards compatible, no-one should be relying on it being a particular class, they should attempt to call the documented function and let classes quack as they do in Python!

**Comment by whiteroses** [comment]
I suppose some of the ducks can sound the same when they all inherit from `Accept` :) But yeah, I can't think of why someone would. So I submitted the PR &mdash; would you rather I close the issue from the commit or PR, or let you do it?

**Comment by whiteroses** [comment]
Btw the new `AcceptEncoding` class is not yet in the docs, but that's the next PR, as many of the classes in acceptparse.py also need documenting.

**Comment by bertjwregeer** [comment]
Feel free to create another ticket for changing the Accept-Encoding to actually follow the RFC, or keep this one open. Up to you :-)

**Comment by whiteroses** [comment]
I'll close this one, as this particular issue is resolved. Was just wondering if me closing the issue via pull request (https://github.com/blog/1506-closing-issues-via-pull-requests) would mean less work for you :)

**Comment by whiteroses** [comment]
It probably doesn't make any difference to you, but as I opened the issues, I guess I should just close them myself, whether via pull request or not. Will do that from now on, no worries :)
