### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by corehack** [Pylons/webob#331]
Parts of WebOb haven't been adapted to work in IPv6 environment:
- request.domain will split IPv6 addresses incorrectly
- request.host_port will split IPv6 addresses incorrectly
- request.host_url will split IPv6 addresses incorrectly
- .. maybe more places, I haven't checked all sources

This issue is similar to #174 however there it's about mitigating potential vulnerabilities and this issue is only about making API work correctly. Software using WebOb can workaround this by parsing the Host header manually, but it's just wasteful because everybody has to repeat the same work, that should be done by WebOb (as promised by the API)

**Comment by mmerickel** [comment]
It would help a lot of you could push a pull request with some failing asserts for various apis or just a python gist we could run. Even actual examples in a comment here. Anything to get us on the same page about what "incorrectly" means a bit faster.

**Comment by bertjwregeer** [comment]
This is only an issue if the remote is directly connecting to a WSGI service, and the browser is sending a Host header that looks like this:

`Host: [2001:DB8::1]:6453`

I've fixed this in #332. In the usual case of WebOb parsing a request that contains a Host header that is a valid domain there are no issues. It is unlikely anyone is directly visiting `http://[2001:DB8::1]:6453` in their browser to reach their site, knowing IPv6 addresses.

**Comment by corehack** [comment]
It's unlikely generally for websites, yes. However for localhost it's totally valid case and probably not very rare simply because `::1` is much shorter

**Comment by bertjwregeer** [comment]
Even then that is unlikely, users tend to use `localhost` instead and use resolution.

**Comment by corehack** [comment]
Well, there are standards - either you support it or not. Any API is ok, even if it misbehaves in some cases, if it is documented. Whether or not such API is useful is another topic..
