### ISSUE TITLE
DELETE-request with 'application/x-www-form-urlencoded' content type.

### ISSUE THREAD

**Issue by Cykooz** [Pylons/webob#351]
Property POST of DELETE-request returns `NoVars` despite the fact that Content-Type is 'application/x-www-form-urlencoded'.

**Comment by bertjwregeer** [comment]
That's documented as such:

https://github.com/Pylons/webob/blob/master/src/webob/request.py#L755

I'd be okay with a pull request that changes it so that it is supported on any arbitrary method.

**Comment by bertjwregeer** [comment]
Closed by #352
