### ISSUE TITLE
raise if a media range is passed to best_match

### ISSUE THREAD

**Issue by mmerickel** [Pylons/webob#367]
Versions of webob prior to 1.6 would always raise, but in 1.6, and 1.7 they are treated as ranges and in 1.8 they are treated as media types.

Version 1.5.1:

```
>>> MIMEAccept('text/html').best_match(['text/*'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael/work/oss/pyramid/env27/lib/python2.7/site-packages/webob/acceptparse.py", line 176, in best_match
    if self._match(mask, offer):
  File "/Users/michael/work/oss/pyramid/env27/lib/python2.7/site-packages/webob/acceptparse.py", line 303, in _match
    _check_offer(offer)
  File "/Users/michael/work/oss/pyramid/env27/lib/python2.7/site-packages/webob/acceptparse.py", line 320, in _check_offer
    raise ValueError("The application should offer specific types, got %r" % offer)
ValueError: The application should offer specific types, got 'text/*'
>>> MIMENilAccept().best_match(['text/*'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael/work/oss/pyramid/env27/lib/python2.7/site-packages/webob/acceptparse.py", line 230, in best_match
    _check_offer(offer)
  File "/Users/michael/work/oss/pyramid/env27/lib/python2.7/site-packages/webob/acceptparse.py", line 320, in _check_offer
    raise ValueError("The application should offer specific types, got %r" % offer)
ValueError: The application should offer specific types, got 'text/*'
```

Version 1.7.4:

```
>>> MIMEAccept('text/html').best_match(['text/*'])
'text/*'
>>> MIMENilAccept().best_match(['text/*'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael/work/oss/pyramid/env27/lib/python2.7/site-packages/webob/acceptparse.py", line 209, in best_match
    _check_offer(offer)
  File "/Users/michael/work/oss/pyramid/env27/lib/python2.7/site-packages/webob/acceptparse.py", line 340, in _check_offer
    raise ValueError("The application should offer specific types, got %r" % offer)
ValueError: The application should offer specific types, got 'text/*'
```

Version 1.8.2:

```
>>> create_accept_header('text/html').best_match(['text/*'])
'text/*'
>>> create_accept_header(None).best_match(['text/*'])
'text/*'
>>> create_accept_header('invalid/x/y').best_match(['text/*'])
'text/*'
```

I think the old behavior should be restored and invalid offers should raise.

**Comment by mmerickel** [comment]
this title was adjusted but I think the original was correct as well... `acceptable_offers` should also raise when passed a media range and it doesn't right now.

**Comment by mmerickel** [comment]
ok, for clarity, #365 is about `acceptable_offers` and this issue is about the bw-compat issues in `best_match`.

**Comment by whiteroses** [comment]
The only change in behaviour between 1.7 and 1.8 was that calls to `_check_offer` in `NilAccept.__contains__` and `NilAccept.best_match` (what are now `_AcceptInvalidOrNoHeader.__contains__` and `_AcceptInvalidOrNoHeader.best_match`) were removed to match the behaviour of `MIMEAccept.__contains__` and `MIMEAccept.best_match` and [the docstring of `MIMEAccept._match`](https://github.com/Pylons/webob/blob/1.7-branch/webob/acceptparse.py#L282), which allowed media types/ranges with `*`s in them. No other changes were made, as the plan was to deprecate `__contains__` and `best_match`, so the only difference in behaviour between 1.7 and 1.8 is that `ValueError` is no longer raised when an offer with a `*` in it meets a header that would previously have been a `MIMENilAccept`.

I see now that the docstrings for `__contains__` and `best_match` were never even updated after the change to accept ranges in 1.6 ([issue](https://github.com/Pylons/webob/issues/155) and [PR](https://github.com/ltvolks/webob/commit/8f49817f64833fc9171e506ad648314dc7d9a246)), with both docstrings referring only to types &mdash; so essentially it was an under-the-hood change in WebOb for Pyramid, and WebOb users would not have even known about the change to accept ranges without seeing mention of it in the changelog or the issue and PR. I don't know why I didn't see that the docstrings for `__contains__` and `best_match` hadn't been updated, or if I did why it didn't give me pause. Given all this, I would support restoring `_check_offer` calls to `best_match` and `__contains__`, especially as we can see from your example from 1.7.4 that `MIMEAccept.best_match` wasn't even working properly with ranges:

    >>> MIMEAccept('text/html').best_match(['text/*'])
    'text/*'

This is returning the offer &mdash; a range &mdash; as the best match.

Adding `_check_offer` calls should be relatively simple, but should we remove the code that was added to handle ranges too?

**Comment by mmerickel** [comment]
No we shouldn't remove the code but I do think a PR to bring back the `_check_offer` calls would be nice to keep the api bw-compatible until it's removed.

**Comment by whiteroses** [comment]
@mmerickel I submitted a PR, but I think leaving behind the code that handles `*`s in offers but removing the tests means failing coverage. What should I do?

**Comment by mmerickel** [comment]
I'm sorry @whiteroses I'm reading this all again and it seems to me that my advice made no sense. It has been very confusing for me to keep all these inconsistencies straight as I've been uncovering them.

I originally opened this issue when I didn't realize that `best_match` actually supported wildcards. It seems to me that since it does support wildcards, and that you actually did make the api consistent in 1.8 (note that the `best_match` does not raise on the examples at the bottom of the ticket). Therefore, I think I should just close this issue. Does this make sense to you?

**Comment by whiteroses** [comment]
@mmerickel: It's frequently very confusing for me too! It's a lot of details to keep in our heads.

I think you're right, so I'll close the PR &mdash; thanks.
