### ISSUE TITLE
AcceptInvalidHeader should not accept anything

### ISSUE THREAD

**Issue by mmerickel** [Pylons/webob#368]
webob 1.8.2:

```
>>> create_accept_header('foo').acceptable_offers(['text/html'])
[('text/html', 1.0)]
```

versus webob 1.7.4:

```
>>> MIMEAccept('foo').best_match(['text/html'])
>>>
```

The correct behavior, and what I expect for a correct implementation of accept handling in pyramid is the version in 1.7.4 where an invalid header does not match anything, allowing the user to define a default view.

**Comment by mmerickel** [comment]
Further, there is no simple way to detect an invalid header. The `bool(request.accept)` only distinguishes valid from invalid/missing. My only option is to use `isinstance(request.accept, webob.acceptparse.AcceptInvalidHeader)`. Ideally there would be `request.accept.is_invalid`, `request.accept.is_missing` and `request.accept.is_valid` I think if we need care so much about these different states.

**Comment by bertjwregeer** [comment]
I don't think we need to care about the different states, to be quite honest, unless there is a good reason for doing so.

**Comment by mmerickel** [comment]
ok I'm closing this one, I don't think I care that much about missing versus invalid and I think, at the end of the day, the behavior of an "invalid" header is ambiguous and treating it as missing is fine.
