### ISSUE TITLE
AcceptLanguageValidHeader.lookup has unused local variable

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/webob#382]
```
src/webob/acceptparse.py:4611:17: F841 local variable 'asterisk_non0_found' is assigned to but never used
```

@whiteroses, could you take a look at this? It looks like you are assigning to but never using `asterisk_non0_found` in the code.

**Comment by whiteroses** [comment]
There's no need for `asterisk_non0_found`; I submitted https://github.com/Pylons/webob/pull/383 to remove it and tidy things up. Sorry about that!

**Comment by bertjwregeer** [comment]
No worries, and thanks!
