### ISSUE TITLE
New release for Python 3.6?

### ISSUE THREAD

**Issue by fschulze** [Pylons/webob#393]
Would you consider making a new release soon? There are several fixes on master which make WebOb work with Python 3.6 like the backslash escape cleanups.

**Comment by bertjwregeer** [comment]
Which fixes are on master and not on 1.8-branch?

**Comment by fschulze** [comment]
For example:

https://github.com/Pylons/webob/blob/1.8-branch/src/webob/acceptparse.py#L2479

vs

https://github.com/Pylons/webob/blob/master/src/webob/acceptparse.py#L2534

The former has ``\ `` in it which causes a SyntaxError in Python 3.6. The commit in question is https://github.com/Pylons/webob/commit/5c062aef9397b27915c5cc2ed2f202bff7494eca, but there may be more.

**Comment by bertjwregeer** [comment]
It shouldn't cause a SyntaxError, it should be a warning.

**Comment by bertjwregeer** [comment]
```
/Users/xistence/Projects/Pylons/webob/.tox/py36/lib/python3.6/site-packages/webob/acceptparse.py:2493: DeprecationWarning: invalid escape sequence \
```

That DeprecationWarning is only shown once, during the conversion from .py to .pyc (compile). There has been no good way to actually figure out how to make it error when its run in `tox` so it was missed when all the others were fixed.

**Comment by bertjwregeer** [comment]
https://pypi.org/project/WebOb/1.8.5/

**Comment by fschulze** [comment]
Thanks! That fixes it. I also figured out why it's happening. I use buildout, which doesn't compile the .py files to .pyc on install. When I then run the tests with pytest, it turns the DeprecationWarning into an error on first import. If I import WebOb before running pytest and the .pyc files are there, it works.
