### ISSUE TITLE
webob.multidict.MultiDict.items() returns iterator instead of list

### ISSUE THREAD

**Issue by benvc** [Pylons/webob#395]
Per the documentation for [webob.multidict.MultiDict.items()](https://docs.pylonsproject.org/projects/webob/en/stable/api/multidict.html#webob.multidict.MultiDict.items), this method should return a list. Instead it returns an iterator. Not hard to work around, but either the documentation should be updated or the method should be fixed. Simple repro:

```
from webob.multidict import MultiDict

m = MultiDict()
m.add('key', 'value')
items = m.items()
exhausted = list(items)
print(exhausted)
# [('key', 'value')]
print(list(items))
# [] 
```

**Comment by bertjwregeer** [comment]
Are you on Py3 or Py2?

**Comment by bertjwregeer** [comment]
The documentation needs to be updated, but it follows the same conventions as `dict` on the platform. So on Py3 `.items()` is an iterator not a list that is returned.

**Comment by benvc** [comment]
Sorry, Python 3.6

**Comment by bertjwregeer** [comment]
Yeah, this is as expected. I'll get the docs updated.

**Comment by benvc** [comment]
Makes sense and explains why the method is not deprecated since it would behave differently in Py2. Thanks.

**Comment by bertjwregeer** [comment]
I've updated the Read the Docs build to use Python 3 instead of Python 2. That does mean that the documentation will no longer contain the Python 2 equivalents.
