### ISSUE TITLE
minor doc link fix

### ISSUE THREAD

**Issue by bwduncan** [Pylons/webob#418]
https://github.com/Pylons/webob/blob/ac2d238f50bed7fbbf115818ab7f208b71d7bdca/src/webob/response.py#L735

This should be `14.15`:

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.15

**Comment by stevepiercy** [comment]
Would you please submit a PR with this correction? Thank you!

**Comment by stevepiercy** [comment]
Closed by #419
