### ISSUE TITLE
schedule for next release?

### ISSUE THREAD

**Issue by d70-t** [Pylons/webob#425]
Thank you for building webob. I am only indirectly using it through the pydap library, but that is a central piece for our current workflow. I came here to fix #424 and am very happy about the quick and easy merge 🎉. However, this issue is still blocking our progress considerably as we'd like to require only released pieces of code as our dependencies. This is why I am now filing this issue.

The last release of webob is now [more than a year old](https://github.com/Pylons/webob/releases/tag/1.8.6) and there are quite a few new additions to it (github counts 170 commits). Is there a new release planned soon?

**Comment by stevepiercy** [comment]
@mmerickel @bertjwregeer is there anything blocking a new release of webob? I can step in if granted access to PyPI (stevepiercy) and follow [RELEASING.rst](https://github.com/Pylons/webob/blob/master/RELEASING.rst).

**Comment by bertjwregeer** [comment]
@stevepiercy there's a lot of documentation that needs to be written/rewritten on the features/changes that were made. I need to validate it works against current versions of Pyramid as well to make sure nothing was broken in the Py2 removal.

There's a couple of other issues that should probably get fixed too. 

Overall webob `master` as it currently stands is not in a state where I'd feel comfortable just releasing it without doing more work on it. So as of right now, there is a lot blocking a new release.

Sadly the time I have to work on the project is low, and my mental health as it stands is not in an ideal spot either.

@d70-t @stevepiercy: If you want to back port the change and open a PR against the 1.8-branch I can cut a new release for that.

**Comment by stevepiercy** [comment]
Backporting the feature to 1.8.x should be easy enough. @d70-t can you take that on? A release with that feature would happen much faster with you as its champion. Please let us know.

**Comment by stevepiercy** [comment]
@bertjwregeer would it help to create or assign existing issues, label them as blockers to a release of `master` as `2.0-branch`, and assign them to a 2.0 milestone? Then the community can knock them off as time allows. Or maybe you have another idea?

**Comment by d70-t** [comment]
@bertjwregeer and @stevepiercy thank you for suggesting this way forward. I created a corresponding PR. Thanks for helping out and I feel sorry for the hassle involved with it.

**Comment by bertjwregeer** [comment]
@d70-t I have uploaded version 1.8.7 to PyPI: https://pypi.org/project/WebOb/1.8.7/

Thank you!
