### ISSUE TITLE
Documentation only shows calling from repl

### ISSUE THREAD

**Issue by chriscamacho** [Pylons/webob#443]
to a new comer to WebOb, everything looks great, exactly what's needed, however as *all* the examples - even the write your own framework, only show examples from the repl or from the built-in web server, its not at all obvious how to use WebOb with mod_wsgi

It would be nice to show an absolute minimal mod_wsgi usable hello world "app" that shows how to integrate WebOb.

I'll bodge something via trial and error eventually I guess, but it would be nice if the docs were explicit in this case.

**Comment by chriscamacho** [comment]
I used a decorator I found on a blog post...
`def wsgiwrap(func):
    def wsgi_app(environ, start_response):
        req = Request(environ)
        try:
            resp = func(req)
        except (exc.HTTPException, e):
            resp = e
        return resp(environ, start_response)
    return wsgi_app

@wsgiwrap
def simple_app(req):
    ....

application = simple_app 
`
This seems to work, but no idea if this is how it's intended to be used from the current documentation...

**Comment by mmerickel** [comment]
The right answer for how to do this is https://docs.pylonsproject.org/projects/webob/en/stable/api/dec.html#webob.dec.wsgify. Open to any PRs to improve the docs but I think I'm going to mark this closed for now.
