### ISSUE TITLE
uploading (large) files using HTTP POST forces me to write them twice

### ISSUE THREAD

**Issue by alekibango** [Pylons/webob#60]
i am doing api for uploading many files. Some of them are really large (even 40 GB).

i would love to use POST (as i have many other fields to send along)...
That stores temporary files on disk -> and forces me to read it back and write it elsewhere.

It would be sweet if i could just move the file... 
When stored on the same filesystem, this will be much more efficient.

**Comment by alekibango** [comment]
For other users transfering big files, i would like to leave few notes about how i solved it years back:

- using PUT is making more sense in such cases, as it contains raw data stream.
- if possible, rather split files into smaller pieces.
- consider not using http. It is not simple nor nice.
- many pythonic frameworks have different funny problems with uploading files bigger than 2 GB, and/or  with HTTP 1.1 features, like chunked encoding.  Be sure to test your app well!

**Comment by bertjwregeer** [comment]
The WSGI server is the actually the one that stores the file on disk, not WebOb. Also, as it currently stands, using POST it gets parsed by Python's CGIFieldStorage which may be storing another copy.

**Comment by mcdonc** [comment]
I doubt you could just move the file anyway, as during a POST the body is probably multipart/mime-encoded and has the file part as only one of the sections.  But it would be great if someone tried a deep dive into the code to see how many times the file gets copied and if some of those copies could be avoided, even if it only helped with PUT.
